### ISSUE TITLE
✨ TODO

### ISSUE THREAD

**Issue by wu-clan** [fastapi-practices/fastapi_best_architecture#258]
## It would be great if you could provide PR.

We've fully upgraded to Pydantic-V2, but we still have some unfinished business from V1 that we'll continue to push in V2!

- [x] Dynamic Configuration (site title, logo, footer...) #365 
- [x] code generation #318 
- [x] File Upload: Docking cloud OSS and local backup. #489 
- [x] System Notification: ws? python-socketio? #437

News:

- [x] New backend architecture #299 #300
- [x] OAuth2 application #293
- [x] Reconstruct role menu permissions #264
- [x] Official website: [fastapi_best_architecture_docs](https://fastapi-practices.github.io/fastapi_best_architecture_docs/)
- [x] New CRUDBase #317
- [x] Hot-swappable plug-in #503

**Comment by downdawn** [comment]
Fastapi Upgrade Starlette to >=0.29.0,<0.33.0
[https://github.com/tiangolo/fastapi/releases/tag/0.108.0](https://github.com/tiangolo/fastapi/releases/tag/0.108.0)

Sqlmodel will support for Pydantic 2.0
[https://github.com/tiangolo/sqlmodel/issues/654](https://github.com/tiangolo/sqlmodel/issues/654)

**Comment by wu-clan** [comment]
> Sqlmodel will support for Pydantic 2.0
https://github.com/tiangolo/sqlmodel/issues/654

Check out the list of organizational warehouses and you'll be amazed!

**Comment by wu-clan** [comment]
I got an update push from fastapi but I'm watching https://github.com/encode/starlette/pulls and there are some amazing updates here, if they are merged Fastapi will need to continue to adapt Starlette-1.0.0, will these minor versions continue to be compatible? I'm not sure, but I don't want to consume time for minor versions.

**Comment by downdawn** [comment]
These projects share common developers, and we will continue to monitor them. 
Our existing project structure is already quite stable, with no significant issues for production. 
The current three-tier architecture appears to have room for further optimization, possibly by integrating SQLModel or other methods.

**Comment by wu-clan** [comment]
> Our existing project structure is already quite stable, with no significant issues for production.

That's so cool, a solid architecture .

SQLModel is an ORM, we already have SQLA, what are your thoughts?

Repo: [here](https://github.com/fastapi-practices/fastapi_sqlmodel_mysql)

**Comment by downdawn** [comment]
SQLModel is both an SQLAlchemy model and a Pydantic model, so there is a possibility to further merge and simplify 'models' and 'schemas'. 

We can keep an eye on this progress:
**Migration from SQLAlchemy to SQLModel.**
[https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/541](https://github.com/tiangolo/full-stack-fastapi-postgresql/issues/541)

**Comment by wu-clan** [comment]
I agree with you, but I'll decline the offer.

Because SQLModel is not updated and fixed at a good pace and is missing documentation, in fact SQLModel was born here: https://github.com/tiangolo/pydantic-sqlalchemy to reduce manual schema definition and validation is great in my opinion;

Although the number of stars for SQLModel is promising, the number of users for it is much lower than for SQLA, and to use SQLModel, the users have to learn it as well，unless SQLModel is really all over the place, I'd migrate to it

**Comment by downdawn** [comment]
OK, I agree with you

**Comment by nipeone** [comment]
I'm a bit confused about the services layer, why not use the inheritance structure like the CRUD layer instead of using static functions? If  use inheritance， simple create/retrieve/update/delete/ can be generalised

**Comment by wu-clan** [comment]
Hi, @nipeone, there may be typos in the question

As I understand it, this sounds like an interesting idea, reviewing the current structure, it does seem to be flawed, but I would prioritize the singleton pattern over class inheritance, everyone, talk about what your think!

**Comment by wu-clan** [comment]
Hi, @everyone

I've created a new question to discuss your ideas together: #269
